version: '3.8'

services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    volumes:
      - prometheus_conf:/opt/bitnami/prometheus/conf
      - prometheus_data:/opt/bitnami/prometheus/data
    networks:
      - cicd
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    networks:
      - cicd 
    ports:
      - "3000:3000"
volumes:
  prometheus_conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: config
  prometheus_data:

networks:
  cicd:
    external: true