version: '3.8'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.2
    container_name: logstash
    hostname: logstash
    volumes:
      - logstash_settings:/usr/share/logstash/config
      - logstash_pipeline:/usr/share/logstash/pipeline
    ports:
      - "31311:31311"
    networks:
      - cicd
volumes:
  logstash_settings:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\\python\\docker\\docker_jenkins\\logstash\\settings\\
  logstash_pipeline:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\\python\\docker\\docker_jenkins\\logstash\\pipeline\\

networks:
  cicd:
    external: true