version: '3.8'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.2.2
    container_name: logstash
    hostname: logstash
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./settings:/usr/share/logstash/config
    networks:
      - cicd
networks:
  cicd:
    external: true